name: barry_callebaut
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.13.1
  firebase_auth: ^3.3.9
  cloud_firestore: ^3.1.10
  firebase_storage: ^10.2.16
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  animated_bottom_navigation_bar: ^1.0.1
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.0
  dotted_border: ^2.0.0+2
  syncfusion_flutter_charts: ^20.2.43
  im_stepper: ^1.0.1+1
  image_picker: ^0.8.5+3
  percent_indicator: ^4.2.2
  permission_handler: ^10.0.0
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  printing: ^5.9.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"

flutter:

  uses-material-design: true
  
  assets:
    - assets/logo.svg
    - assets/icon1.svg
    - assets/icon2.svg
    - assets/icon3.svg
    - assets/icon4.svg
    - assets/icon5.svg
    - assets/pin.png
  
  fonts: 
    - family: Poppins
      fonts:
      - asset: fonts/Poppins-Thin.ttf
        weight: 100
      - asset: fonts/Poppins-ExtraLight.ttf
        weight: 200
      - asset: fonts/Poppins-Light.ttf
        weight: 300
      - asset: fonts/Poppins-Regular.ttf
        weight: 400
      - asset: fonts/Poppins-Medium.ttf
        weight: 500
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 800
      - asset: fonts/Poppins-Black.ttf
        weight: 900
    - family: CustomIcons
      fonts:
      - asset: fonts/CustomIcons.ttf